name: 01-2. Greet Everyone
# This workflow is triggered on pushes to the repository.
on: 
  
  workflow_call:
    inputs:
      name:
        description: 'What is your name?'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      name:
        description: 'What is your name?'
        required: false
        default: 'Octocat'
 
jobs:
  greet-users:
    name: Greeting
    # This job runs on Linux
    runs-on: [self-hosted]
    steps:
      # This step uses GitHub's hello-world-javascript-action: 
      # https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "${{ github.event.inputs.name }}${{ inputs.name }}"
        id: hello

