name: 02-2. Dependencies 

on:
  push:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
    
jobs:
  initial:
    runs-on: self-hosted
    steps:
      - run: echo "This job will be run first."
